- name: Install wget
  yum:
    name: wget
    state: latest
    update_cache: yes 
- name: install Java 8
  yum:
    name: openjdk-8-jdk
    state: latest
- name: Create nexus User
  user:
    name: nexus
    state: present
    shell: /bin/bash
- name: create installation dir
  file:
    path: /opt/nexus
    state: directory
    mode: 0755
- name: Download nexus
  unarchive:
    src: http://download.sonatype.com/nexus/3/nexus-3.15.2-01-unix.tar.gz
    dest: /opt/nexus/
    remote_src: yes
  args:
    creates: /opt/nexus/nexus-3.15.2-01
- name: Change /opt/nexus/ owner
  file:
    path: /opt/nexus/
    owner: nexus
    group: nexus
    recurse: yes
- name: configure nexus to run with user nexus
  lineinfile:
    path: /opt/nexus/nexus-3.15.2-01/bin/nexus.rc
    line: "run_as_user=\"nexus\""
- name: create service nexus
  file:
    src: /opt/nexus/nexus-3.15.2-01/bin/nexus
    dest: /etc/init.d/nexus
    state: link
- name: start nexus
  service:
    name: nexus
    state: started
    enabled: true
